/**
 * validateapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Validateapi);
  }
}(this, function(expect, Validateapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Validateapi.WhoisResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WhoisResponse', function() {
    it('should create an instance of WhoisResponse', function() {
      // uncomment below and update the code to test WhoisResponse
      //var instane = new Validateapi.WhoisResponse();
      //expect(instance).to.be.a(Validateapi.WhoisResponse);
    });

    it('should have the property validDomain (base name: "ValidDomain")', function() {
      // uncomment below and update the code to test the property validDomain
      //var instane = new Validateapi.WhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property whoisServer (base name: "WhoisServer")', function() {
      // uncomment below and update the code to test the property whoisServer
      //var instane = new Validateapi.WhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property rawTextRecord (base name: "RawTextRecord")', function() {
      // uncomment below and update the code to test the property rawTextRecord
      //var instane = new Validateapi.WhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdDt (base name: "CreatedDt")', function() {
      // uncomment below and update the code to test the property createdDt
      //var instane = new Validateapi.WhoisResponse();
      //expect(instance).to.be();
    });

  });

}));
