---
swagger: "2.0"
info:
  version: "v1"
  title: "ocrapi"
host: "api.cloudmersive.com"
schemes:
- "https"
paths:
  /ocr/image/toText:
    post:
      tags:
      - "ImageOcr"
      summary: "Converts an uploaded image in common formats such as JPEG, PNG into\
        \ text via Optical Character Recognition."
      operationId: "ImageOcr_Post"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/json"
      - "application/xml"
      - "text/xml"
      parameters:
      - name: "imageFile"
        in: "formData"
        description: "Image file to perform OCR on.  Common file formats such as PNG,\
          \ JPEG are supported."
        required: true
        type: "file"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ImageToTextResponse"
      x-swagger-router-controller: "ImageOcr"
securityDefinitions:
  Apikey:
    description: "API Key Authentication"
    type: "apiKey"
    name: "Apikey"
    in: "header"
definitions:
  ImageToTextResponse:
    type: "object"
    properties:
      MeanConfidenceLevel:
        type: "number"
        format: "float"
      TextResult:
        type: "string"
    description: "Response from an OCR to text operation.  Includes the confience\
      \ rating and converted text result."
    example:
      TextResult: "TextResult"
      MeanConfidenceLevel: 0.8008282
