/**
 * barcodeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BarcodeLookupResponse', 'model/ProductMatch', 'cloudmersive-barcode-api-client/BarcodeLookupApi', 'cloudmersive-barcode-api-client/GenerateBarcodeApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/BarcodeLookupResponse'), require('./model/ProductMatch'), require('./cloudmersive-barcode-api-client/BarcodeLookupApi'), require('./cloudmersive-barcode-api-client/GenerateBarcodeApi'));
  }
}(function(ApiClient, BarcodeLookupResponse, ProductMatch, BarcodeLookupApi, GenerateBarcodeApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Barcodeapi = require('index'); // See note below*.
   * var xxxSvc = new Barcodeapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Barcodeapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Barcodeapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Barcodeapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BarcodeLookupResponse model constructor.
     * @property {module:model/BarcodeLookupResponse}
     */
    BarcodeLookupResponse: BarcodeLookupResponse,
    /**
     * The ProductMatch model constructor.
     * @property {module:model/ProductMatch}
     */
    ProductMatch: ProductMatch,
    /**
     * The BarcodeLookupApi service constructor.
     * @property {module:cloudmersive-barcode-api-client/BarcodeLookupApi}
     */
    BarcodeLookupApi: BarcodeLookupApi,
    /**
     * The GenerateBarcodeApi service constructor.
     * @property {module:cloudmersive-barcode-api-client/GenerateBarcodeApi}
     */
    GenerateBarcodeApi: GenerateBarcodeApi
  };

  return exports;
}));
