/**
 * validateapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Validateapi) {
      root.Validateapi = {};
    }
    root.Validateapi.AddressGetServersResponse = factory(root.Validateapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AddressGetServersResponse model module.
   * @module model/AddressGetServersResponse
   * @version v1
   */

  /**
   * Constructs a new <code>AddressGetServersResponse</code>.
   * @alias module:model/AddressGetServersResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AddressGetServersResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddressGetServersResponse} obj Optional instance to populate.
   * @return {module:model/AddressGetServersResponse} The populated <code>AddressGetServersResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Success')) {
        obj['Success'] = ApiClient.convertToType(data['Success'], 'Boolean');
      }
      if (data.hasOwnProperty('Servers')) {
        obj['Servers'] = ApiClient.convertToType(data['Servers'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} Success
   */
  exports.prototype['Success'] = undefined;
  /**
   * @member {Array.<String>} Servers
   */
  exports.prototype['Servers'] = undefined;



  return exports;
}));


