/**
 * nlpapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CheckJsonResponse', 'model/CheckSentenceJsonResponse', 'model/CorrectJsonResponse', 'model/CorrectWordInSentenceJsonResponse', 'model/GetWordsJsonResponse', 'model/LanguageDetectionResponse', 'model/PosRequest', 'model/PosResponse', 'model/PosSentence', 'model/PosTaggedWord', 'model/WordPosition', 'cloudmersive-nlp-api-client/ApikeyUsageApi', 'cloudmersive-nlp-api-client/ExtractEntitiesStringApi', 'cloudmersive-nlp-api-client/LanguageDetectionApi', 'cloudmersive-nlp-api-client/ParseStringApi', 'cloudmersive-nlp-api-client/PosTaggerJsonApi', 'cloudmersive-nlp-api-client/PosTaggerStringApi', 'cloudmersive-nlp-api-client/SentencesApi', 'cloudmersive-nlp-api-client/SpellCheckApi', 'cloudmersive-nlp-api-client/WordsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CheckJsonResponse'), require('./model/CheckSentenceJsonResponse'), require('./model/CorrectJsonResponse'), require('./model/CorrectWordInSentenceJsonResponse'), require('./model/GetWordsJsonResponse'), require('./model/LanguageDetectionResponse'), require('./model/PosRequest'), require('./model/PosResponse'), require('./model/PosSentence'), require('./model/PosTaggedWord'), require('./model/WordPosition'), require('./cloudmersive-nlp-api-client/ApikeyUsageApi'), require('./cloudmersive-nlp-api-client/ExtractEntitiesStringApi'), require('./cloudmersive-nlp-api-client/LanguageDetectionApi'), require('./cloudmersive-nlp-api-client/ParseStringApi'), require('./cloudmersive-nlp-api-client/PosTaggerJsonApi'), require('./cloudmersive-nlp-api-client/PosTaggerStringApi'), require('./cloudmersive-nlp-api-client/SentencesApi'), require('./cloudmersive-nlp-api-client/SpellCheckApi'), require('./cloudmersive-nlp-api-client/WordsApi'));
  }
}(function(ApiClient, CheckJsonResponse, CheckSentenceJsonResponse, CorrectJsonResponse, CorrectWordInSentenceJsonResponse, GetWordsJsonResponse, LanguageDetectionResponse, PosRequest, PosResponse, PosSentence, PosTaggedWord, WordPosition, ApikeyUsageApi, ExtractEntitiesStringApi, LanguageDetectionApi, ParseStringApi, PosTaggerJsonApi, PosTaggerStringApi, SentencesApi, SpellCheckApi, WordsApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Nlpapi = require('index'); // See note below*.
   * var xxxSvc = new Nlpapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Nlpapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Nlpapi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Nlpapi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CheckJsonResponse model constructor.
     * @property {module:model/CheckJsonResponse}
     */
    CheckJsonResponse: CheckJsonResponse,
    /**
     * The CheckSentenceJsonResponse model constructor.
     * @property {module:model/CheckSentenceJsonResponse}
     */
    CheckSentenceJsonResponse: CheckSentenceJsonResponse,
    /**
     * The CorrectJsonResponse model constructor.
     * @property {module:model/CorrectJsonResponse}
     */
    CorrectJsonResponse: CorrectJsonResponse,
    /**
     * The CorrectWordInSentenceJsonResponse model constructor.
     * @property {module:model/CorrectWordInSentenceJsonResponse}
     */
    CorrectWordInSentenceJsonResponse: CorrectWordInSentenceJsonResponse,
    /**
     * The GetWordsJsonResponse model constructor.
     * @property {module:model/GetWordsJsonResponse}
     */
    GetWordsJsonResponse: GetWordsJsonResponse,
    /**
     * The LanguageDetectionResponse model constructor.
     * @property {module:model/LanguageDetectionResponse}
     */
    LanguageDetectionResponse: LanguageDetectionResponse,
    /**
     * The PosRequest model constructor.
     * @property {module:model/PosRequest}
     */
    PosRequest: PosRequest,
    /**
     * The PosResponse model constructor.
     * @property {module:model/PosResponse}
     */
    PosResponse: PosResponse,
    /**
     * The PosSentence model constructor.
     * @property {module:model/PosSentence}
     */
    PosSentence: PosSentence,
    /**
     * The PosTaggedWord model constructor.
     * @property {module:model/PosTaggedWord}
     */
    PosTaggedWord: PosTaggedWord,
    /**
     * The WordPosition model constructor.
     * @property {module:model/WordPosition}
     */
    WordPosition: WordPosition,
    /**
     * The ApikeyUsageApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/ApikeyUsageApi}
     */
    ApikeyUsageApi: ApikeyUsageApi,
    /**
     * The ExtractEntitiesStringApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/ExtractEntitiesStringApi}
     */
    ExtractEntitiesStringApi: ExtractEntitiesStringApi,
    /**
     * The LanguageDetectionApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/LanguageDetectionApi}
     */
    LanguageDetectionApi: LanguageDetectionApi,
    /**
     * The ParseStringApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/ParseStringApi}
     */
    ParseStringApi: ParseStringApi,
    /**
     * The PosTaggerJsonApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/PosTaggerJsonApi}
     */
    PosTaggerJsonApi: PosTaggerJsonApi,
    /**
     * The PosTaggerStringApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/PosTaggerStringApi}
     */
    PosTaggerStringApi: PosTaggerStringApi,
    /**
     * The SentencesApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/SentencesApi}
     */
    SentencesApi: SentencesApi,
    /**
     * The SpellCheckApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/SpellCheckApi}
     */
    SpellCheckApi: SpellCheckApi,
    /**
     * The WordsApi service constructor.
     * @property {module:cloudmersive-nlp-api-client/WordsApi}
     */
    WordsApi: WordsApi
  };

  return exports;
}));
