/**
 * barcodeapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BarcodeLookupResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/BarcodeLookupResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Barcodeapi) {
      root.Barcodeapi = {};
    }
    root.Barcodeapi.BarcodeLookupApi = factory(root.Barcodeapi.ApiClient, root.Barcodeapi.BarcodeLookupResponse);
  }
}(this, function(ApiClient, BarcodeLookupResponse) {
  'use strict';

  /**
   * BarcodeLookup service.
   * @module cloudmersive-barcode-api-client/BarcodeLookupApi
   * @version v1
   */

  /**
   * Constructs a new BarcodeLookupApi. 
   * @alias module:cloudmersive-barcode-api-client/BarcodeLookupApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the barcodeLookupEanLookup operation.
     * @callback module:cloudmersive-barcode-api-client/BarcodeLookupApi~barcodeLookupEanLookupCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BarcodeLookupResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Lookup a barcode value and return product data
     * @param {String} value Barcode value
     * @param {module:cloudmersive-barcode-api-client/BarcodeLookupApi~barcodeLookupEanLookupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BarcodeLookupResponse}
     */
    this.barcodeLookupEanLookup = function(value, callback) {
      var postBody = value;

      // verify the required parameter 'value' is set
      if (value === undefined || value === null) {
        throw new Error("Missing the required parameter 'value' when calling barcodeLookupEanLookup");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = BarcodeLookupResponse;

      return this.apiClient.callApi(
        '/barcode/lookup/ean', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
