/**
 * nlpapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CorrectWordInSentenceJsonResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CorrectWordInSentenceJsonResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Nlpapi) {
      root.Nlpapi = {};
    }
    root.Nlpapi.CheckSentenceJsonResponse = factory(root.Nlpapi.ApiClient, root.Nlpapi.CorrectWordInSentenceJsonResponse);
  }
}(this, function(ApiClient, CorrectWordInSentenceJsonResponse) {
  'use strict';




  /**
   * The CheckSentenceJsonResponse model module.
   * @module model/CheckSentenceJsonResponse
   * @version v1
   */

  /**
   * Constructs a new <code>CheckSentenceJsonResponse</code>.
   * Result of spell checking a sentence
   * @alias module:model/CheckSentenceJsonResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CheckSentenceJsonResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckSentenceJsonResponse} obj Optional instance to populate.
   * @return {module:model/CheckSentenceJsonResponse} The populated <code>CheckSentenceJsonResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IncorrectCount')) {
        obj['IncorrectCount'] = ApiClient.convertToType(data['IncorrectCount'], 'Number');
      }
      if (data.hasOwnProperty('Words')) {
        obj['Words'] = ApiClient.convertToType(data['Words'], [CorrectWordInSentenceJsonResponse]);
      }
    }
    return obj;
  }

  /**
   * Number of incorrect words
   * @member {Number} IncorrectCount
   */
  exports.prototype['IncorrectCount'] = undefined;
  /**
   * Words in the sentence, both correct and incorrect
   * @member {Array.<module:model/CorrectWordInSentenceJsonResponse>} Words
   */
  exports.prototype['Words'] = undefined;



  return exports;
}));


