/**
 * nlpapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WordPosition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WordPosition'));
  } else {
    // Browser globals (root is window)
    if (!root.Nlpapi) {
      root.Nlpapi = {};
    }
    root.Nlpapi.GetWordsJsonResponse = factory(root.Nlpapi.ApiClient, root.Nlpapi.WordPosition);
  }
}(this, function(ApiClient, WordPosition) {
  'use strict';




  /**
   * The GetWordsJsonResponse model module.
   * @module model/GetWordsJsonResponse
   * @version v1
   */

  /**
   * Constructs a new <code>GetWordsJsonResponse</code>.
   * Words in input string
   * @alias module:model/GetWordsJsonResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>GetWordsJsonResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetWordsJsonResponse} obj Optional instance to populate.
   * @return {module:model/GetWordsJsonResponse} The populated <code>GetWordsJsonResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Words')) {
        obj['Words'] = ApiClient.convertToType(data['Words'], [WordPosition]);
      }
    }
    return obj;
  }

  /**
   * Array of words
   * @member {Array.<module:model/WordPosition>} Words
   */
  exports.prototype['Words'] = undefined;



  return exports;
}));


