/**
 * nlpapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Nlpapi) {
      root.Nlpapi = {};
    }
    root.Nlpapi.PosTaggedWord = factory(root.Nlpapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PosTaggedWord model module.
   * @module model/PosTaggedWord
   * @version v1
   */

  /**
   * Constructs a new <code>PosTaggedWord</code>.
   * Word tagged in a POS tag
   * @alias module:model/PosTaggedWord
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PosTaggedWord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PosTaggedWord} obj Optional instance to populate.
   * @return {module:model/PosTaggedWord} The populated <code>PosTaggedWord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Word')) {
        obj['Word'] = ApiClient.convertToType(data['Word'], Object);
      }
      if (data.hasOwnProperty('Tag')) {
        obj['Tag'] = ApiClient.convertToType(data['Tag'], Object);
      }
    }
    return obj;
  }

  /**
   * Word that was tagged
   * @member {Object} Word
   */
  exports.prototype['Word'] = undefined;
  /**
   * Penn Treebank tag applied to the word
   * @member {Object} Tag
   */
  exports.prototype['Tag'] = undefined;



  return exports;
}));


